### ISSUE TITLE
Caster has no currBuildingOrder.

### ISSUE THREAD

**Issue by MNoya** [stephenfournier/Dota-2-Building-Helper#45]
Not sure what causes this [BuildingHelper] Error: Caster has no currBuildingOrder, sometimes it happens more than twice in a row while attempting to repeat the order

**Comment by AeroHand** [comment]
i found this error 2 weeks ago and i tried to fix this with many efforts
this only happens to some rows and if u try to build the building in that place for several times u will finally get success

this error might caused by the building square not appropriate get the building place vector. but im not sure since some part of BH still remains mysterious for me

**Comment by MNoya** [comment]
Fixed in next
