### ISSUE TITLE
Buildings pulled

### ISSUE THREAD

**Issue by nikitinalexx** [stephenfournier/Dota-2-Building-Helper#50]
Hi! First of all thank you for your great job. I just wanted to ask you some questions.
You say that 2.1v is multiplayer oriented, does that mean that 2v will not work if 2+ players? Then what is it intended for? I can hardly imagine someone would play a custom map solo.
I run a 2.1v example. Rocket launcher is displayed as a 1v1 grid. Arrow tower is 2v2 grid. But you said that all should be 2v2. Is this a bug?
And often if you place buildings close to each other, they pull each other! And ruin the grid. Do you know about this issue? I could also make screenshots but this is very easy to reproduce. Is this also a known bug?
Also could you make a guide on how to install 2.1v? Because if i follow 2v guide - you say that i should copy particles folder, but in 2.1v you say that particles were removed

**Comment by Myll** [comment]
Both 2 and 2.1 work with multiplayer, but the ghost can be very laggy in 2 due to not having clientside particles. 2.1 uses scaleform movieclip to display the ghost, which is completely clientside and has 0 lag, but isn't as visually attractive as particles.

Scaleform is being deprecated for panorama. BH is being updated to panorama by snipplets, but we still can't make clientside particles. Currently I think people should just use AOERadius KV for the ghost.

Also sorry I can't be bothered to work on BH now due to other obligations.

**Comment by MNoya** [comment]
Fixed in next
