### ISSUE TITLE
Ghost system

### ISSUE THREAD

**Issue by nikitinalexx** [stephenfournier/Dota-2-Building-Helper#52]
Hi, i found nearlly an ideal system in a map "Dota Builder". The ghost perfectly follows a mouse and moreover perfectly fits the grid in any position and in any distance. In your code you made presumptions to place a green ghost but in this map there are definitely no presumptions since the degree of how the model is shown is really nearlly perfect. Do you have any ideas how did they make it?

**Comment by snipplets** [comment]
Are you able to post a link to their github or workshop page? I'm
interested to see how they did it.

**Comment by nikitinalexx** [comment]
Okay, i'm noob lol. I extracted their files and took a look. They are definitely using your v.2 system. I'm so confused since if i copy your github project or if i follow installation notes i get totally different results. At least now i know that v.2 system perfectly snapped to grid. And this is the thing that confused me, since v.2.1 iF fully copied from github had particles but didn't snap to grid at all... Could you please explain to me this difference? Why in v.2 it did snap to grid but in v.21 it doesn't? I thought that the problem with particles was only in performance, but not in snapping or not snapping to grid.

**Comment by nikitinalexx** [comment]
And btw, if you want to take a look at sources, just get a map file, and extract it (there are tools in web). Good to see how the things in a map are done.

**Comment by space-jam-** [comment]
V2 is able to snap to the grid accurately because the ghost is a particle rendered on the server that is made using proper gridnav coordinates. In addition to this, it is skewed and appears different to a 2d ghost (what is made in scaleform and panorama) because it is and object in the game world, and its dimensions change based on the players perspective.

Basically for scaleform/panorama imagine you have a piece of paper on your screen and move it around and have to change its size to represent the ghost, because we don't know exactly what transformations to make so that it appears to be in the game world. The reason we can't use the particle based solution is that so far there is no way to properly render particles on the client's machine in the game world. Doing them on the server means that while they work for the host, they have huge lag for the clients.
