### ISSUE TITLE
Building health during construction incorrect

### ISSUE THREAD

**Issue by ynohtna92** [stephenfournier/Dota-2-Building-Helper#68]
It seems that when auto constructing the health reaches max before the building is finished, when it should be done at the same time.

**Comment by MNoya** [comment]
This might be an issue with the fast ticking timer with float-carry of @snipplets
Check out if their version at vampirism has fixed it

**Comment by snipplets** [comment]
You're setting the initial building health to 10% of the max whereas I had it starting at 1hp.

You can patch it by doing any of the following:
* Building starting HP is 1
* Set the building complete time to GameTime + buildTime * 0.9 -- imo this is retarded, since the actual build time will be 90% of what the dev sets it as
* Changing the nHealthInterval value [set here](https://github.com/stephenfournier/Dota-2-Building-Helper/blob/master/game/dota_addons/samplerts/scripts/vscripts/buildinghelper.lua#L534) to use buildTime * 1.1

Preference would be option 1 or 3.

**Comment by MNoya** [comment]
Got it, I'll try to implement option 3 with a global key for initial health% somewhere instead of forcing 10%
